// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package impl

import (
	"github.com/anon-org/arithmetic/api"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Wire() *Handler {
	service := ProvideService()
	handler := ProvideHandler(service)
	return handler
}

// wire.go:

var (
	ProviderSet wire.ProviderSet = wire.NewSet(
		ProvideService,
		ProvideHandler, wire.Bind(new(api.Service), new(*Service)), wire.Bind(new(api.Handler), new(*Handler)),
	)
)

func ProvideService() *Service {
	return &Service{}
}

func ProvideHandler(service api.Service) *Handler {
	return &Handler{
		Svc: service,
	}
}
