// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/anon-org/pet/api"
	"github.com/anon-org/pet/service/internal/impl"
)

// Injectors from wire.go:

func Wire(db map[string]*api.User) *impl.Service {
	repository := impl.ProvideRepository(db)
	service := impl.ProvideService(repository)
	return service
}
